name: Export and Publish
env:
  BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
  ITCH_GAME: ${{ secrets.ITCH_GAME }}
  ITCH_USER: ${{ secrets.ITCH_USER }}
on:
  push:
    branches: [main]
permissions: write-all

jobs:
  build-game:
    name: Build game for each platform
    strategy:
      fail-fast: false
      matrix:
        platform:
          [
            { name: linux, target: x86_64-unknown-linux-gnu },
            { name: macos, target: aarch64-apple-darwin },
            { name: web, target: wasm32-unknown-unknown },
            { name: windows, target: x86_64-pc-windows-gnu },
          ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          target: ${{ matrix.platform.target }}
          toolchain: stable
      - name: Cargo build
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target=${{ matrix.platform.target }}
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact-${{ matrix.platform.name }}
          path: target/release/${{ matrix.platform.target }}
  create-release:
    name: Generate a release
    needs: build-game
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download artifacts
        id: download-artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: artifact-*
          path: artifacts
          merge-multiple: true
      - name: Get version
        id: get-version
        run: echo "VERSION=$(grep -o -P '(?<=version = ").*(?=")' Cargo.toml)" >> $GITHUB_OUTPUT
      - name: Get changelog
        id: get-changelog
        run: |
          VERSIONS=$(grep "^## \[.*]" ChangeLog.md)
          FIRST_TWO=$(echo "$VERSIONS" | head -2)
          START=$(echo "$FIRST_TWO" | head -1 | sed -e 's/[]\/$*.^[]/\\&/g')
          END=$(echo "$FIRST_TWO" | tail -1 | sed -e 's/[]\/$*.^[]/\\&/g')
          BODY=$(sed -n -r "/$START/,/$END/p" ChangeLog.md | head -n -1)
          echo 'CHANGELOG<<EOF' >> $GITHUB_OUTPUT
          echo "$BODY" >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          body: ${{ steps.get-changelog.outputs.CHANGELOG }}
          files: ${{ steps.download-artifacts.outputs.download-path }}/*
          tag_name: ${{ steps.get-version.outputs.VERSION }}
  deploy-pages:
    needs: build-game
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: Download web artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact-web
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: artifact-web
  deploy-itch:
    needs: build-game
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: artifact-*
      - name: Deploy Windows build
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          CHANNEL: windows
          PACKAGE: artifact-windows.zip
      - name: Deploy Linux build
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          CHANNEL: linux
          PACKAGE: artifact-linux.zip
      - name: Deploy macOS build
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          CHANNEL: osx
          PACKAGE: artifact-macos.zip
      - name: Deploy web build
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          CHANNEL: html5
          PACKAGE: artifact-web.zip
